# Define substitution variables for better control and version management.
substitutions:
  _TF_VERSION: '1.13.5' # Specific Terraform version for plan and apply steps.
  _PROJECT_ID: "green-energy-tracker-cloud"
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

availableSecrets:
  tf_prod_vars_secret:
    secretManager:
      secretUrl: projects/${_PROJECT_ID}/secrets/terraform-prod-vars/versions/latest
    env: '_TF_VARS'

steps:
  # --- 0. Inject Secrets ---
  - id: 'Inject Secrets'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "$${_TF_VARS}" > variables.tfvars.json'
    dir: './environments/prod'
    secretEnv: [ '_TF_VARS' ]

  # --- Step 1: Initialize Terraform ---
  # 'init' prepares the working directory, downloads providers, and configures the backend state.
  - id: 'Init'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    args: ['init']
    waitFor: ['Inject Secrets']
    dir: './environments/prod'
    secretEnv: ['_TF_VARS']

  # --- Step 2: Generate Execution Plan ---
  # 'plan' inspects the current state, compares it with the configuration, 
  # and saves the proposed changes to the 'tfplan' file.
  - id: 'Plan'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    args: [
      'plan',
      '-var-file=variables.tfvars.json',
      '-out=tfplan'
    ]
    dir: './environments/prod'
    waitFor: [ 'Init' ]
    secretEnv: [ '_TF_VARS' ]

  # --- Step 3: Apply the Changes ---
  # 'apply' executes the changes defined in the 'tfplan' file against the infrastructure.
  - id: 'Apply'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    args: ['apply', 'tfplan']
    waitFor: ['Plan']
    dir: './environments/prod'
